# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\worksrc\VSCODE_PROJ\PythonCode\PyPlayerSelf\PlayerWeight.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FreePlayer(object):
    def setupUi(self, FreePlayer):
        FreePlayer.setObjectName("FreePlayer")
        FreePlayer.resize(388, 84)
        FreePlayer.setStyleSheet("background: rgb(0, 111, 162);")
        self.PyPlayer = QtWidgets.QWidget(FreePlayer)
        self.PyPlayer.setObjectName("PyPlayer")
        self.btnPlay = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPlay.setGeometry(QtCore.QRect(40, 10, 31, 31))
        self.btnPlay.setObjectName("btnPlay")
        self.lineEdit = QtWidgets.QLineEdit(self.PyPlayer)
        self.lineEdit.setGeometry(QtCore.QRect(70, 10, 241, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btnDel = QtWidgets.QPushButton(self.PyPlayer)
        self.btnDel.setGeometry(QtCore.QRect(0, 50, 31, 31))
        self.btnDel.setObjectName("btnDel")
        self.btnPop = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPop.setGeometry(QtCore.QRect(78, 50, 31, 31))
        self.btnPop.setObjectName("btnPop")
        self.btnBlues = QtWidgets.QPushButton(self.PyPlayer)
        self.btnBlues.setGeometry(QtCore.QRect(116, 50, 31, 31))
        self.btnBlues.setObjectName("btnBlues")
        self.btnCountry = QtWidgets.QPushButton(self.PyPlayer)
        self.btnCountry.setGeometry(QtCore.QRect(156, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnCountry.setFont(font)
        self.btnCountry.setIconSize(QtCore.QSize(16, 16))
        self.btnCountry.setObjectName("btnCountry")
        self.btnMetal = QtWidgets.QPushButton(self.PyPlayer)
        self.btnMetal.setGeometry(QtCore.QRect(194, 50, 31, 31))
        self.btnMetal.setObjectName("btnMetal")
        self.btnPunk = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPunk.setGeometry(QtCore.QRect(234, 50, 31, 31))
        self.btnPunk.setObjectName("btnPunk")
        self.btnHard = QtWidgets.QPushButton(self.PyPlayer)
        self.btnHard.setGeometry(QtCore.QRect(272, 50, 31, 31))
        self.btnHard.setObjectName("btnHard")
        self.btnPause = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPause.setGeometry(QtCore.QRect(310, 10, 31, 31))
        self.btnPause.setObjectName("btnPause")
        self.btnPre = QtWidgets.QPushButton(self.PyPlayer)
        self.btnPre.setGeometry(QtCore.QRect(0, 10, 31, 31))
        self.btnPre.setObjectName("btnPre")
        self.btnNext = QtWidgets.QPushButton(self.PyPlayer)
        self.btnNext.setGeometry(QtCore.QRect(350, 10, 31, 31))
        self.btnNext.setObjectName("btnNext")
        self.btnSolo = QtWidgets.QPushButton(self.PyPlayer)
        self.btnSolo.setGeometry(QtCore.QRect(40, 50, 31, 31))
        self.btnSolo.setObjectName("btnSolo")
        self.btnExit = QtWidgets.QPushButton(self.PyPlayer)
        self.btnExit.setGeometry(QtCore.QRect(350, 50, 36, 31))
        self.btnExit.setObjectName("btnExit")
        self.btnJapan = QtWidgets.QPushButton(self.PyPlayer)
        self.btnJapan.setGeometry(QtCore.QRect(310, 50, 31, 31))
        self.btnJapan.setObjectName("btnJapan")
        FreePlayer.setCentralWidget(self.PyPlayer)

        self.retranslateUi(FreePlayer)
        QtCore.QMetaObject.connectSlotsByName(FreePlayer)

    def retranslateUi(self, FreePlayer):
        _translate = QtCore.QCoreApplication.translate
        FreePlayer.setWindowTitle(_translate("FreePlayer", "MainWindow"))
        self.btnPlay.setText(_translate("FreePlayer", ">"))
        self.btnDel.setText(_translate("FreePlayer", "DEL"))
        self.btnPop.setText(_translate("FreePlayer", "POP"))
        self.btnBlues.setText(_translate("FreePlayer", "BLUE"))
        self.btnCountry.setText(_translate("FreePlayer", "CTY"))
        self.btnMetal.setText(_translate("FreePlayer", "METAL"))
        self.btnPunk.setText(_translate("FreePlayer", "PUNK"))
        self.btnHard.setText(_translate("FreePlayer", "HD R"))
        self.btnPause.setText(_translate("FreePlayer", "||"))
        self.btnPre.setText(_translate("FreePlayer", "<<"))
        self.btnNext.setText(_translate("FreePlayer", ">>"))
        self.btnSolo.setText(_translate("FreePlayer", "SOLO"))
        self.btnExit.setText(_translate("FreePlayer", "EXIT"))
        self.btnJapan.setText(_translate("FreePlayer", "JP"))
