# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\worksrc\VSCODE_PROJ\PythonCode\PyPlayerSelf\RandomPlayWeight.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 95)
        MainWindow.setStyleSheet("background-color: rgb(0, 111, 162);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 291, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btnPlay = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlay.setGeometry(QtCore.QRect(65, 50, 41, 41))
        self.btnPlay.setObjectName("btnPlay")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(130, 50, 51, 41))
        self.btnDel.setObjectName("btnDel")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(250, 50, 51, 41))
        self.btnExit.setObjectName("btnExit")
        self.btnPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnPause.setGeometry(QtCore.QRect(200, 50, 41, 41))
        self.btnPause.setObjectName("btnPause")
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(10, 50, 41, 41))
        self.btnNext.setObjectName("btnNext")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPlay.setText(_translate("MainWindow", ">"))
        self.btnDel.setText(_translate("MainWindow", "DEL"))
        self.btnExit.setText(_translate("MainWindow", "EXIT"))
        self.btnPause.setText(_translate("MainWindow", "||"))
        self.btnNext.setText(_translate("MainWindow", ">>"))
